Feature/update organisation schema
Healthy-London-Partnership/api pull request #13
Opened 2020-09-14 10:59 UTC by appsol

- Added polymorphic fields to social_medias
- Migrate existing service_id relationship to polymorphic relationship
- Added social_medias node to organisations api using schema from services
- Added location_id relationship to organisations
- Updated organisations url, email, phone fields to be nullable
- Added location_id node to organisations api
- Updated docs and ERD

2020-09-14 15:17 UTC, matthew-inamdar requested changes
Looks good 👍 

I've merged in `develop` and manually resolved the database ERD changes - it's a bit of a pain since it's a binary file 🙁 

The API definition seems to be invalid when viewing them on Swagger UI: http://localhost/docs

Let's have the `OrganisationController::index()`` method eager load the `location` and `socialMedias` relationships as part of the base query. Otherwise, we'll run into an n+1 issue.

There are some changes requested for the migrations that might be an issue. We use enums in the database and due to the doctrine issues with enums, we may need to construct manual statements. Feel free to give me a shout if you come across any.

Can we also make the migration rollbacks work with existing data? I'm a bit concerned around columns that have become nullable. We've done something similar here: 
https://github.com/Healthy-London-Partnership/api/blob/31486c1ee4942404a4e480d397721d16de3fdfd9/database/migrations/2020_09_14_100517_make_phone_column_nullable_on_users_table.php#L10-L38

2020-09-14 15:17 UTC, matthew-inamdar commented on tests/Feature/OrganisationsTest.php
> +        ]);
Could we do this to make the test a bit more explicit?

```suggestion
        $this->assertDatabaseHas(table(Organisation::class), [
            'id' => $organisation->id,
            'location_id' => null,
        ]);
```

2020-09-15 11:52 UTC, appsol commented on app/Http/Controllers/Core/V1/OrganisationController.php
> +                    'social_medias' => $request->missing('social_medias'),
Done.

2020-09-15 11:52 UTC, appsol commented on app/Models/Organisation.php
> +        }
Done.

2020-09-15 11:53 UTC, appsol commented on database/migrations/2020_09_09_151448_update_social_medias_add_polymorphic_fields.php
> +            $table->nullableUuidMorphs('sociable');
Done. Had to do this manually as the macro does not return the table object to allow chaining.

2020-09-15 11:53 UTC, appsol commented on database/migrations/2020_09_09_151448_update_social_medias_add_polymorphic_fields.php
> +        if (Schema::hasColumn('social_medias', 'service_id')) {
Done.

2020-09-15 11:55 UTC, appsol commented on database/migrations/2020_09_09_151448_update_social_medias_add_polymorphic_fields.php
> +                DB::update('update social_medias set sociable_id = service_id, sociable_type = ? where service_id is not null', [\App\Models\Service::class]);
Done. I used UpdateRequest::EXISTING_TYPE_SERVICE so as not to leave strings in the code.

2020-09-15 11:55 UTC, appsol commented on database/migrations/2020_09_10_090840_update_organisations_add_location_id_and_make_fields_optional.php
> +            $table->string('phone');
Done.

2020-09-15 11:55 UTC, appsol commented on database/migrations/2020_09_10_090840_update_organisations_add_location_id_and_make_fields_optional.php
> +            $table->nullableForeignUuid('location_id', 'locations');
Done. I had to abandon the macro as it does not allow method chaining.

2020-09-15 11:56 UTC, appsol commented on database/migrations/2020_09_10_090840_update_organisations_add_location_id_and_make_fields_optional.php
> +        });
Done. I wrapped them in separate functions as SQLite will choke on this.

2020-09-15 11:57 UTC, appsol commented on tests/Feature/OrganisationsTest.php
> +        // dd($response);
Done. (oops)

2020-09-15 11:57 UTC, appsol commented on tests/Feature/OrganisationsTest.php
> +        ]);
Done.

2020-09-15 12:40 UTC, matthew-inamdar commented on database/migrations/2020_09_10_090840_update_organisations_add_location_id_and_make_fields_optional.php
> +        });
Ah, that makes sense. We're tightly coupled to MySQL for this app, so we're safe to use MySQL specific syntax/statements for future work.

2020-09-15 12:41 UTC, matthew-inamdar commented on database/migrations/2020_09_09_151448_update_social_medias_add_polymorphic_fields.php
> +                DB::update('update social_medias set sociable_id = service_id, sociable_type = ? where service_id is not null', [\App\Models\Service::class]);
That should be fine. I try to leave app code out of the migrations in the event that the values changewhich cause issues when running migrations from scratch in the future.

2020-09-15 12:44 UTC, matthew-inamdar submitted a review, later dismissed
LGTM 👍 

To fix the code style violations, you should be able to run `./develop composer fix:style` and it should do most of it for you (if not all) 🙂

2020-09-16 13:29 UTC, appsol commented
Ran fix:style

2020-09-18 09:52 UTC, appsol commented on database/migrations/2020_09_10_090840_update_organisations_add_location_id_and_make_fields_optional.php
> +            $table->string('phone')->nullable()->change();
This has been done.

2020-09-18 09:53 UTC, appsol commented on database/migrations/2020_09_09_151448_update_social_medias_add_polymorphic_fields.php
> +                DB::update('update social_medias set service_id = sociable_id where sociable_type = ? and sociable_id is not null', [\App\Models\Service::class]);
`DB::update('update social_medias set sociable_id = service_id, sociable_type = ? where service_id is not null', [UpdateRequest::EXISTING_TYPE_SERVICE]);`

Changed: Referenced the definition to avoid raw strings in the code.

2020-09-18 15:05 UTC, merged