Feature/bulk import organisations
Healthy-London-Partnership/api pull request #17
Opened 2020-09-20 14:39 UTC by appsol

### Bulk import of organisations

- Ref: https://trello.com/c/NUDw7odt
- Import and validate rows from .xls or .xlsx spreadsheet
- Returns total organisations imported or details of failing rows
- If any row fails no organisation is imported

2020-09-22 15:27 UTC, matthew-inamdar requested changes
Looks good - I love the use of generators 👍 

Some comments left. Feel free to drop me a message if you want to go over any of them.

2020-09-22 15:27 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +                $rowBatch[] = $row;
Can we add the `created_at` and `updated_at` timestamps?

```suggestion
                $row['id'] = (string) Str::uuid();
                $row['slug'] = Str::slug($row['name'] . ' ' . uniqid(), '-');
                $row['created_at'] = Date::now();
                $row['updated_at'] = Date::now();
                $rowBatch[] = $row;
```

2020-09-22 15:27 UTC, matthew-inamdar commented on app/Http/Requests/Organisation/ImportRequest.php
> +                'regex:/^data:application\/vnd[a-z\-\.]+;base64,/',
This seems to fail when attempting to upload `.xls` file. It works fine with a `.xlsx` file.

Vue devtools whos the base64 encoded file as `data:application/octet-stream;base64,0M8R...` for `.xls`.

2020-09-22 15:41 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +        Log::info($request->input('spreadsheet'));
Done (sorry).

2020-09-22 15:41 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +        Log::info($filePath);
Done (sorry again).

2020-09-22 15:53 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +    public function importSpreadsheet(String $filePath)
Done.

2020-09-22 15:53 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +    public function validateSpreadsheet(String $filePath)
Done.

2020-09-22 15:53 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +    public function storeBase64FileString(string $file_data, string $path)
Done.

2020-09-22 15:53 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +    public function storeBinaryUpload(string $blob, string $path, $mime_type = null, $ext = null)
Done.

2020-09-22 15:59 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +        Storage::disk('local')->delete($filePath);
Done.

2020-09-22 15:59 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +                $rowBatch[] = $row;
Done.

2020-09-23 09:48 UTC, appsol commented on app/Http/Controllers/Core/V1/Organisation/ImportController.php
> +                DB::table('organisations')->insert($rowBatch);
I've added in another transaction that bulk creates the Organisation Admins. This should be fine as we are working on the theory that these are all new organisations. It doesn't appear to add appreciably to the processing time and I have included it in the transaction so if anything goes wrong nothing is committed to disk.

2020-09-23 10:29 UTC, matthew-inamdar approved these changes
LGTM 👍  Nice work on this!

2020-09-23 10:31 UTC, merged