Feature/add national service option
Healthy-London-Partnership/api pull request #25
Opened 2020-09-23 16:36 UTC by appsol

### Add in a new "national" service option

Ref: https://trello.com/c/fDs5TiSH

- Added Migration for Boolean is_national field. Defaults to true.
- Updated Service model and factory to reflect change
- Added is_national to Service validation for create and update
- Create Rule IsLocalService to check the Service is_national flag.
- Updated the ServiceLocation validation to prevent allocating locations to national services
- Added is_national to search parameters for Services
- Created tests to check for filter by both is_national == true and is_national == false

2020-09-23 17:17 UTC, matthew-inamdar requested changes
Really good stuff! Left a comment regarding indexing the new column, but apart from that, this looks really solid 💪

2020-09-24 10:03 UTC, appsol commented on database/migrations/2020_09_22_131554_add_is_national_field_to_services.php
> +            $table->boolean('is_national')->after('status')->default(true);
I'm happy to do it if you think it's worthwhile, but I'm not sure the gains from indexing a boolean field will be that much.

2020-09-24 10:09 UTC, matthew-inamdar commented on database/migrations/2020_09_22_131554_add_is_national_field_to_services.php
> +            $table->boolean('is_national')->after('status')->default(true);
It's worth putting it in now as it doesn't take much time. It's one less thing to worry about if we need to scale this up to support many more services.

2020-09-24 10:22 UTC, appsol commented on database/migrations/2020_09_22_131554_add_is_national_field_to_services.php
> +            $table->boolean('is_national')->after('status')->default(true);
Done.

2020-09-24 12:33 UTC, matthew-inamdar submitted a review, later dismissed

2020-09-24 12:33 UTC, matthew-inamdar commented
Waiting to merge until https://github.com/Healthy-London-Partnership/admin/pull/13 is also ready.

2020-09-24 12:38 UTC, matthew-inamdar requested changes
The code looks great 👍 

When manual testing, I noticed you can have an existing non-national service with a service location, and then update it to become national.

We should prevent this from happening with request validation.

2020-09-24 15:41 UTC, appsol commented
Requested changes completed.

2020-09-25 08:57 UTC, matthew-inamdar approved these changes

2020-09-25 09:47 UTC, merged