Feature/add advice service type
Healthy-London-Partnership/api pull request #27
Opened 2020-09-24 11:53 UTC by appsol

### Add new service type for 'Advice'
https://trello.com/c/DWAqk1Ew

- created test to check all service types could be created
- created migration to add 'advice' as an option to the enum field service::type.
- Added advice type class constant to Service
- Added advice type to request validation for store and update
- Added advice type to search parameter
- Added advice to options in Service OpenAPI specs
- Updated the ERD to reflect changes

### Development checklist
- [1 ] Changes have been made to the API?
  - [1 ] If so, the OpenAPI specification has been updated
- [1 ] Database migrations have been added?
  - [ 1] If so, the MySQL Workbench ERD has been updated
- [1 ] The code has been linted `./develop composer fix:style`

### Release checklist
- None

### Notes
NA

2020-09-25 10:09 UTC, matthew-inamdar requested changes
Looking good 👍 

I've left a comment on the migration to add rollback support for existing app type services.

I've also noted the following:

- [ ] The API docs for the search endpoint need updating `app/Docs/Schemas/Search/StoreSearchSchema.php:33`
- [ ] The API docs for updating a service need updating `app/Docs/Schemas/Service/UpdateServiceSchema.php:60`
- [ ] The store org sign up form request validation needs updating `app/Http/Requests/OrganisationSignUpForm/StoreRequest.php:91`
- [ ] The search request validation needs updating `app/Http/Requests/Search/Request.php:45`

Will test once changes have been made.

2020-09-26 13:09 UTC, matthew-inamdar commented
I've merged in the new commits from `develop` and manually resolved the ERD conflicts.

2020-09-28 12:59 UTC, appsol commented on database/migrations/2020_09_24_111142_update_services_add_advice_to_types_enum.php
> +        DB::statement(
Makes sense. Done.

2020-09-28 16:19 UTC, matthew-inamdar approved these changes

2020-09-29 18:52 UTC, merged