Feature/add national service option
Healthy-London-Partnership/api pull request #30
Opened 2020-10-01 09:04 UTC by appsol

### Summary
https://trello.com/c/fDs5TiSH

- Added is_national field to search API docs
- Prevent attempting location search if is_national is true
- Added parameters to is_national search test

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
Merged in develop prior to commit

2020-10-01 18:06 UTC, matthew-inamdar requested changes
Looking good 👍  

I've left a few comments to take a look at.

2020-10-01 18:06 UTC, matthew-inamdar commented on tests/Feature/SearchTest.php
> +            'view' => 'grid',
There isn't a `view` parameter which the controller accepts. Is there a reason this was added?

2020-10-01 18:06 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/SearchController.php
> +        if ($request->has('location') && !$request->is_national) {
Instead of doing this extra condition, could we make the condition above an `elseif`? This would make the code easier to follow.

```php
if ($request->has('location')) {
    //...
} elseif ($request->is_national) {
    //...
}
```

2020-10-02 08:19 UTC, appsol commented on app/Http/Controllers/Core/V1/SearchController.php
> +        // dd($search->getQuery());
Done.

2020-10-02 08:21 UTC, appsol commented on tests/Feature/SearchTest.php
> +            'view' => 'grid',
I put this in as it formed part of the query that Sean was using and was not getting results on. I noticed that I couldn't see a view parameter on the controller, but wanted to include it as part of debugging Sean's issue. I've removed it now as the issue was resolved by re-indexing.

2020-10-02 08:30 UTC, appsol commented on app/Http/Controllers/Core/V1/SearchController.php
> +        if ($request->has('location') && !$request->is_national) {
Agree that is better. However as the acceptance also required the search to be able to find non-national services I've left the conditionals as:
`if ($request->has('location')) {
        //...
 } elseif ($request->has('is_national')) {
        // Apply filter on `is_national` field.
        $search->applyIsNational((bool) $request->is_national);
 }`

2020-10-06 20:25 UTC, matthew-inamdar approved these changes

2020-10-06 20:25 UTC, merged