Feature/bulk import services
Healthy-London-Partnership/api pull request #31
Opened 2020-10-01 16:58 UTC by appsol

### Summary
https://trello.com/c/mkseo25s

- Create services/import path
- Refactor spreadsheet parsing functionality from Organisations import
- Add isAdmin filter to organisation index
- Update php and Nginx config to increase script timeout to 300 seconds

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
- [ ] Build Docker images on deploy

### Notes
NA

2020-10-06 20:57 UTC, matthew-inamdar requested changes
Looking really good 👍 

Left some questions and comments to check out.

2020-10-06 20:57 UTC, matthew-inamdar commented on app/Contracts/SpreadsheetController.php
> +<?php
What's the purpose of this interface? I can't seem to see any code which expects an implementation of it.

2020-10-06 20:57 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/OrganisationController.php
> +                Filter::custom('is_admin', IsAdminFilter::class),
Can this be added to the OpenAPI spec?

2020-10-06 20:57 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/Service/ImportController.php
> +        if (!(new IsOrganisationAdmin($this->user))->passes('id', $this->organisationId)) {
Can this be added to the `ImportRequest` as a validation rule?

2020-10-06 20:57 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/Service/ImportController.php
> +            $organisationAdminIds = Role::organisationAdmin()->users()->pluck('users.id');
This will get every organisation admin, regardless of the organisation. We need this to only get organisation admins for the organisation the services are uploaded for.

2020-10-06 20:57 UTC, matthew-inamdar commented on app/Http/Requests/Service/ImportRequest.php
> +            return $this->user()->isOrganisationAdmin(Organisation::findOrFail($this->organisation_id))
There's no need for the conditionals after this first check to `isOrganisationAdmin()`, as the method already contains logic to check for higher roles.

2020-10-07 15:52 UTC, appsol commented on app/Contracts/SpreadsheetController.php
> +<?php
Used by:

`App\Http\Controllers\Core\V1\Organisation\ImportController
App\Http\Controllers\Core\V1\Service\ImportController`

Both use the trait StoresSpreadsheets which expects some methods on the classes in which it is used.

2020-10-07 15:55 UTC, appsol commented on app/Http/Controllers/Core/V1/OrganisationController.php
> +                Filter::custom('is_admin', IsAdminFilter::class),
Done

2020-10-07 16:36 UTC, appsol commented on app/Http/Controllers/Core/V1/Service/ImportController.php
> +        if (!(new IsOrganisationAdmin($this->user))->passes('id', $this->organisationId)) {
To be honest, looking at it again, I'm not sure it's required. I think the authorize method on the Import Request already covers this:
`
if ($this->user()) {
            return $this->user()->isOrganisationAdmin(Organisation::findOrFail($this->organisation_id));
        }
`

2020-10-07 16:37 UTC, appsol commented on app/Http/Controllers/Core/V1/Service/ImportController.php
> +            $organisationAdminIds = Role::organisationAdmin()->users()->pluck('users.id');
Refactored to limit to only organisation admins of the context organisation:
`
$organisationAdminIds = $this->organisation
                ->users()
                ->where('user_roles.role_id', Role::organisationAdmin()->id)
                ->pluck('users.id');
`

2020-10-07 16:37 UTC, appsol commented on app/Http/Requests/Service/ImportRequest.php
> +            return $this->user()->isOrganisationAdmin(Organisation::findOrFail($this->organisation_id))
Done

2020-10-07 21:06 UTC, matthew-inamdar commented on app/Contracts/SpreadsheetController.php
> +<?php
I don't think an interface makes sense for this use case. I'd expect to see it used when we're type-hinting for an instance of an interface. 

By using the trait alone, we can rely on the methods existing. Can we remove it?

2020-10-07 21:07 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/Service/ImportController.php
> +        if (!(new IsOrganisationAdmin($this->user))->passes('id', $this->organisationId)) {
Cool, let's remove it then 👍

2020-10-08 09:39 UTC, appsol commented on app/Http/Controllers/Core/V1/Service/ImportController.php
> +        if (!(new IsOrganisationAdmin($this->user))->passes('id', $this->organisationId)) {
Removed

2020-10-08 09:39 UTC, appsol commented on app/Contracts/SpreadsheetController.php
> +<?php
Removed

2020-10-08 19:56 UTC, merged