Feature/add app store links
Healthy-London-Partnership/api pull request #33
Opened 2020-10-08 14:57 UTC by appsol

### Summary
https://trello.com/c/QnNWmmpV

- At least 1 of ios_app_url or android_app_url must be added if creating a service of type 'app'
- ios_app_url or android_app_url must be a valid url
- both fields are optional if not a service of type 'app'

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
Refactored the Tests\Feature\ServicesTest to use generator methods for common payload data.

2020-10-12 19:59 UTC, matthew-inamdar requested changes
Looking good. Would be great if we can simplify the update service request validation.

2020-10-12 19:59 UTC, matthew-inamdar commented on app/Http/Requests/Service/UpdateRequest.php
> +                'nullable', 'url', 'max:255', ],
Can we simplify these conditions as they're quite confusing to follow?

I'd rather have more verbose code that's easier to understand.

2020-10-13 10:57 UTC, appsol commented on app/Http/Requests/Service/UpdateRequest.php
> +                'nullable', 'url', 'max:255', ],
Fair point. Hopefully should be clearer now.

2020-10-13 18:57 UTC, matthew-inamdar approved these changes

2020-10-13 19:28 UTC, merged