add new pages to settings cms
Healthy-London-Partnership/api pull request #35
Opened 2020-10-12 15:12 UTC by appsol

### Summary
https://trello.com/c/biMeXjz6

- Update tests to reflect new content structure
- Create migration to initialise the content structure
- Update request validation to accept new content structure
- Update Controller method to store new content structure

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
NA

2020-10-12 19:29 UTC, matthew-inamdar requested changes
Looking good. The migration needs looking at.

2020-10-12 19:29 UTC, matthew-inamdar commented on database/migrations/2020_10_12_113406_update_settings_table_cms_default_value.php
> +<?php
This is going to override all the current CMS values. We should add the new fields and remove the old ones from the JSON value.

Since we're using MySQL 5.7, we can make use of the JSON column operators. Take a look at how we've achieved this in a previous migration: https://github.com/Healthy-London-Partnership/api/blob/master/database/migrations/2019_06_03_142917_update_sidebox_schema_in_meta_column_of_collections_table.php

2020-10-13 16:03 UTC, appsol commented on database/migrations/2020_10_12_113406_update_settings_table_cms_default_value.php
> +<?php
Good point. TBH I wasn't thinking about existing data, but you're right, there is a production version out and I need to protect existing data. I've rewritten the migration to retain data, but cannot retain all data on rollback as there is a contraction in the number of fields.

2020-10-13 18:52 UTC, matthew-inamdar commented on database/migrations/2020_10_12_113406_update_settings_table_cms_default_value.php
> +<?php
Nice - and not to worry 🙂

2020-10-13 18:52 UTC, matthew-inamdar approved these changes

2020-10-13 18:53 UTC, merged