Feature/search within collection set
Healthy-London-Partnership/api pull request #37
Opened 2020-10-14 17:10 UTC by appsol

### Summary
https://trello.com/c/R2OD8fxL

- Change search parameters persona and category to accept either a single collection slug, or a comma separated set of collection slugs.
- Expanded search tests to ensure query and location searches occur within the specified collections

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
Re-index Elasticsearch

### Notes
NA

2020-10-19 06:53 UTC, matthew-inamdar requested changes
Please see code comments.

OpenAPI spec updates are also needed.

2020-10-19 06:53 UTC, matthew-inamdar commented on app/Http/Controllers/Core/V1/SearchController.php
> +
Please remove.

```suggestion
        // dd($search->getQuery());

```

2020-10-19 06:53 UTC, matthew-inamdar commented on app/Search/ElasticsearchSearch.php
> +
What's the purpose of this? Can we not only use the `terms` query you've done below?

2020-10-19 06:53 UTC, matthew-inamdar commented on app/Search/ElasticsearchSearch.php
> +
What's the purpose of this? Can we not only use the `terms` query you've done below?

2020-10-19 15:32 UTC, appsol commented on app/Http/Controllers/Core/V1/SearchController.php
> +
Sorry, my bad.

2020-10-19 16:16 UTC, appsol commented on app/Search/ElasticsearchSearch.php
> +
Agreed both are very similar, but I was trying to follow the pattern that existed. I've combined it into one method that takes a slug and a type string to either apply a persona or a category filter.

2020-10-19 16:16 UTC, appsol commented on app/Search/ElasticsearchSearch.php
> +
See above

2020-10-19 16:19 UTC, appsol commented
@matthew-inamdar The OpenAPI specs have not changed, the search object still accepts a category or persona string, but these are now slugs, not names. Additionally they can now be either a single slug or a comma separated series of slugs, but either way it is still a string.

2020-10-20 07:30 UTC, matthew-inamdar requested changes
Comments left

2020-10-20 07:30 UTC, matthew-inamdar commented on app/Contracts/Search.php
> +    public function applyCollection(string $category, string $type): Search;
Can we revert this? I think the interface was more explicit and clearer before. Understanding the method implementations may have been almost identical, I'd prefer if we instead used a protected method in the implementation class which these methods could delegate to.

2020-10-20 11:03 UTC, appsol commented on app/Contracts/Search.php
> +    public function applyCollection(string $category, string $type): Search;
I've reverted to the previous api, but as you suggested have centralised the functionality in a protected method which both public methods delegate to.

2020-10-28 21:23 UTC, matthew-inamdar approved these changes

2020-10-28 21:36 UTC, merged