Feature/copy across loop permissions
Healthy-London-Partnership/api pull request #39
Opened 2020-10-19 10:40 UTC by appsol

### Summary
https://trello.com/c/shIP4udB

- Git cherry-pick commits from https://github.com/the-leeds-repo/api/pull/15/commits
- Ran all tests, updating current app to align with new Role management

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
NA

2020-10-29 22:24 UTC, matthew-inamdar requested changes
Looking good 👍 

- There are some failing tests to look at.
- The service import controller must no longer create any roles (org admins will now implicitly be service admins/workers).
- The organisation import controller must no longer create any roles (super/global admins will now implicitly be org admins).

2020-10-30 16:44 UTC, appsol commented
- Organisation\ImportController does not create admins
- Service\ImportController does not create admins
- Updated tests to match
- Fixed failing tests

2020-11-02 22:24 UTC, matthew-inamdar commented
LGTM 👍

2020-11-02 22:24 UTC, matthew-inamdar approved these changes

2020-11-02 22:25 UTC, merged