Feature/advanced admin filters
Healthy-London-Partnership/api pull request #48
Opened 2020-11-05 12:20 UTC by appsol

### Summary
https://trello.com/c/Zl6sXM8H

- Added additional filter options to Social Media filter
- Added additional filter options to Phone filter

### Development checklist
- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist
NA

### Notes
NA

2020-11-08 16:53 UTC, matthew-inamdar requested changes
Looks good. Left a comment to take a look at.

2020-11-08 16:53 UTC, matthew-inamdar commented on app/Http/Filters/Organisation/HasSocialMediasFilter.php
> +                        ->whereRaw('social_medias.sociable_type = ?', [table(Organisation::class)])
The morph map overrides the default:
```suggestion
                        ->whereRaw('social_medias.sociable_type = ?', ['organisations'])
```

https://github.com/Healthy-London-Partnership/api/blob/bef6b85ed66c4c0b1cbedb3829f7c15848d735ff/app/Providers/ModelServiceProvider.php#L56-L61

2020-11-09 14:13 UTC, appsol commented on app/Http/Filters/Organisation/HasSocialMediasFilter.php
> +                        ->whereRaw('social_medias.sociable_type = ?', [table(Organisation::class)])
Done.
Sorry I assumed the table function was designed to work with the morph map. Having had a look inside I can see it just calculates a standard table name. I'll take this into account in future.

2020-11-12 20:53 UTC, matthew-inamdar commented on app/Http/Filters/Organisation/HasSocialMediasFilter.php
> +                        ->whereRaw('social_medias.sociable_type = ?', [table(Organisation::class)])
@appsol Yeah, it does. Sorry I completely missed the use of `table()` - that would have worked. I'd still avoid the use in the case though, as morph map just happens to be using the same name as the tables, but there's nothing stopping that from changing in the future.

2020-11-12 21:01 UTC, matthew-inamdar approved these changes
LGTM 👍

2020-11-12 21:01 UTC, merged